services:
  sip-exporter:
    image: sip-exporter:0.1.0
    container_name: sip-exporter
    restart: unless-stopped
    environment:
      - SIP_EXPORTER_HTTP_PORT=2112
      - SIP_EXPORTER_INTERFACE=lo
    privileged: true # require!
    ports:
      - "2112:2112"
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
    network_mode: "host"  # only host!