FROM alpine:3.22

RUN apk add --no-cache --upgrade libelf bash libssl3 libcrypto3
COPY main /usr/local/bin/main
COPY bin/sip.o /usr/local/bin/sip.o
RUN chmod +x /usr/local/bin/main
HEALTHCHECK CMD wget -qO- "http://localhost:${SIP_EXPORTER_HTTP_PORT:-10047}/health" || exit 1
ENTRYPOINT ["/usr/local/bin/main"]
