//go:build ignore

// Command gen_e164 parses Google libphonenumber PhoneNumberMetadata.xml and
// emits a sorted prefix→ISO table for E.164 country lookup.
//
// Usage: go run gen_e164.go -xml data/PhoneNumberMetadata.xml -out e164_generated.go
package main

import (
	"encoding/xml"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
)

type territories struct {
	Territories []territory `xml:"territories>territory"`
}

type territory struct {
	ID                 string `xml:"id,attr"`
	CountryCode        string `xml:"countryCode,attr"`
	LeadingDigits      string `xml:"leadingDigits,attr"`
	MainCountryForCode bool   `xml:"mainCountryForCode,attr"`
}

func main() {
	xmlPath := flag.String("xml", "", "path to PhoneNumberMetadata.xml")
	outPath := flag.String("out", "", "output Go file path")
	flag.Parse()

	if *xmlPath == "" || *outPath == "" {
		fmt.Fprintln(os.Stderr, "usage: go run gen_e164.go -xml <path> -out <path>")
		os.Exit(1)
	}

	data, err := os.ReadFile(*xmlPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read xml: %v\n", err)
		os.Exit(1)
	}

	var terr territories
	if err := xml.Unmarshal(data, &terr); err != nil {
		fmt.Fprintf(os.Stderr, "parse xml: %v\n", err)
		os.Exit(1)
	}

	mainForCode := map[string]string{}
	// ccTerritories tracks all territories per country code.
	ccTerritories := map[string][]string{}
	type entry struct{ prefix, iso string }
	var entries []entry

	for _, t := range terr.Territories {
		ccTerritories[t.CountryCode] = append(ccTerritories[t.CountryCode], t.ID)
		if t.MainCountryForCode {
			mainForCode[t.CountryCode] = t.ID
		}
		if t.LeadingDigits != "" {
			for _, p := range expandPattern(t.LeadingDigits) {
				entries = append(entries, entry{t.CountryCode + p, t.ID})
			}
		}
	}

	// Bare countryCode entries: for shared codes use mainCountryForCode;
	// for single-territory codes (no mainCountryForCode needed) use the sole territory.
	for cc, isos := range ccTerritories {
		if iso, ok := mainForCode[cc]; ok {
			entries = append(entries, entry{cc, iso})
		} else if len(isos) == 1 {
			entries = append(entries, entry{cc, isos[0]})
		}
	}

	// Supplement: territories sharing a country code without leadingDigits in XML.
	// Canadian area codes (NANP country code 1) are not encoded as leadingDigits;
	// add them explicitly so +1416 → CA, not US.
	for _, ac := range caAreaCodes {
		entries = append(entries, entry{"1" + ac, "CA"})
	}

	seen := map[string]string{}
	for _, e := range entries {
		if existing, ok := seen[e.prefix]; ok && existing != e.iso {
			fmt.Fprintf(os.Stderr, "CONFLICT: prefix %q → %s AND %s\n", e.prefix, existing, e.iso)
		}
		seen[e.prefix] = e.iso
	}

	sortedPrefixes := make([]string, 0, len(seen))
	for p := range seen {
		sortedPrefixes = append(sortedPrefixes, p)
	}
	sort.Sort(byLenDesc(sortedPrefixes))

	var b strings.Builder
	b.WriteString("// Code generated by gen_e164.go; DO NOT EDIT.\n")
	b.WriteString("// Source: Google libphonenumber PhoneNumberMetadata.xml (Apache 2.0)\n\n")
	b.WriteString("package geoip\n\n")
	b.WriteString("// e164PrefixTable maps E.164 digit prefixes to ISO 3166-1 alpha-2 codes.\n")
	b.WriteString("// Longest-prefix match at runtime determines destination country.\n")
	b.WriteString("var e164PrefixTable = map[string]string{\n")
	for _, p := range sortedPrefixes {
		fmt.Fprintf(&b, "\t%q: %q,\n", p, seen[p])
	}
	b.WriteString("}\n")

	if err := os.WriteFile(*outPath, []byte(b.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write output: %v\n", err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "generated %s: %d prefix entries\n", *outPath, len(seen))
}

type byLenDesc []string

func (s byLenDesc) Len() int      { return len(s) }
func (s byLenDesc) Swap(i, j int) { s[i], s[j] = s[j], s[i] }
func (s byLenDesc) Less(i, j int) bool {
	if len(s[i]) != len(s[j]) {
		return len(s[i]) > len(s[j])
	}
	return s[i] < s[j]
}

// caAreaCodes lists Canadian NPA (Numbering Plan Area) codes under NANP
// (country code 1). Canada is the only major NANP territory without
// leadingDigits in libphonenumber metadata, so these must be supplemented
// for correct destination_country resolution.
// Source: https://www.cnac.ca/data/Canadian_NPA_assignment_data.htm
var caAreaCodes = []string{
	"204", "226", "236", "249", "250", "263", "289",
	"306", "343", "354", "365", "367", "368",
	"403", "416", "418", "428", "431", "437", "438",
	"450", "468", "474",
	"506", "514", "519", "548",
	"579", "581", "584", "587",
	"604", "613", "639", "647", "672", "683",
	"705", "709", "742", "753", "778", "780", "782",
	"807", "819", "825",
	"867", "873",
	"902", "905",
}

// expandPattern converts a libphonenumber leadingDigits pattern into concrete
// digit-string prefixes. Supported: literal digits, [3489], [2-9], X|Y, (?:..), XY.
func expandPattern(pattern string) []string {
	tokens := tokenize(pattern)
	return (&parser{tokens: tokens}).parseExpr()
}

type tokenKind int

const (
	tokDigit tokenKind = iota
	tokClass
	tokPipe
	tokLParen
	tokRParen
)

type token struct {
	kind tokenKind
	val  string
	set  []byte
}

func tokenize(pattern string) []token {
	var tokens []token
	i := 0
	for i < len(pattern) {
		switch pattern[i] {
		case '|':
			tokens = append(tokens, token{kind: tokPipe})
			i++
		case '(':
			tokens = append(tokens, token{kind: tokLParen})
			i++
		case ')':
			tokens = append(tokens, token{kind: tokRParen})
			i++
		case '[':
			set, n := parseClass(pattern[i+1:])
			tokens = append(tokens, token{kind: tokClass, set: set})
			i += 1 + n
		case '?', ':':
			i++
		default:
			if pattern[i] >= '0' && pattern[i] <= '9' {
				tokens = append(tokens, token{kind: tokDigit, val: string(pattern[i])})
				i++
			} else {
				panic("unexpected char: " + string(pattern[i]))
			}
		}
	}
	return tokens
}

func parseClass(s string) ([]byte, int) {
	var set []byte
	i := 0
	for i < len(s) && s[i] != ']' {
		if i+2 < len(s) && s[i+1] == '-' {
			for c := s[i]; c <= s[i+2]; c++ {
				set = append(set, c)
			}
			i += 3
		} else {
			set = append(set, s[i])
			i++
		}
	}
	return set, i + 1
}

type parser struct {
	tokens []token
	pos    int
}

func (p *parser) peek() *token {
	if p.pos < len(p.tokens) {
		return &p.tokens[p.pos]
	}
	return nil
}

func (p *parser) next() *token {
	if p.pos < len(p.tokens) {
		t := &p.tokens[p.pos]
		p.pos++
		return t
	}
	return nil
}

func (p *parser) parseExpr() []string {
	result := p.parseTerm()
	for {
		t := p.peek()
		if t == nil || t.kind != tokPipe {
			break
		}
		p.next()
		result = append(result, p.parseTerm()...)
	}
	return result
}

func (p *parser) parseTerm() []string {
	result := []string{""}
	for {
		t := p.peek()
		if t == nil || t.kind == tokPipe || t.kind == tokRParen {
			break
		}
		factors := p.parseFactor()
		merged := make([]string, 0, len(result)*len(factors))
		for _, prefix := range result {
			for _, f := range factors {
				merged = append(merged, prefix+f)
			}
		}
		result = merged
	}
	return result
}

func (p *parser) parseFactor() []string {
	t := p.next()
	if t == nil {
		return []string{""}
	}
	switch t.kind {
	case tokDigit:
		return []string{t.val}
	case tokClass:
		result := make([]string, 0, len(t.set))
		for _, c := range t.set {
			result = append(result, string(c))
		}
		return result
	case tokLParen:
		inner := p.parseExpr()
		if p.peek() != nil && p.peek().kind == tokRParen {
			p.next()
		}
		return inner
	default:
		return []string{""}
	}
}
